--SET CONTEXT
CREATE OR REPLACE WAREHOUSE FACTORY_ANALYTICS_WH
WITH
    WAREHOUSE_SIZE='X-SMALL'
    AUTO_SUSPEND=10
    AUTO_RESUME=TRUE
    INITIALLY_SUSPENDED=TRUE;
    
--CREATE DATABASE
CREATE OR REPLACE DATABASE FACTORY_ANALYTICS_DB;

--CREATE SCHEMAS
CREATE OR REPLACE SCHEMA  FACTORY_ANALYTICS_DB.RAW;
CREATE OR REPLACE SCHEMA  FACTORY_ANALYTICS_DB.CORE;
CREATE OR REPLACE SCHEMA  FACTORY_ANALYTICS_DB.MART;


--SET CONTEXT
USE WAREHOUSE FACTORY_ANALYTICS_WH;
USE DATABASE FACTORY_ANALYTICS_DB;
USE SCHEMA RAW;

--CREATE RAW TABLE


