-- SET CONTEXT
USE WAREHOUSE FACTORY_ANALYTICS_WH;
USE DATABASE FACTORY_ANALYTICS_DB;
USE SCHEMA CORE;


-- CORE FACTORY TABLE
CREATE OR REPLACE TABLE CORE_FACTORY (
    FACTORY_ID STRING PRIMARY KEY,
    FACTORY_NAME STRING,
    CITY STRING,
    OPERATIONAL_STATUS STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);


-- CORE MACHINE TABLE
CREATE OR REPLACE TABLE CORE_MACHINE (
    MACHINE_ID STRING PRIMARY KEY,
    MACHINE_NAME STRING,
    MACHINE_TYPE STRING,
    INSTALLATION_DATE DATE,
    FACTORY_ID STRING,
    MACHINE_STATUS STRING DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);


-- CORE PRODUCTION BATCH TABLE
CREATE OR REPLACE TABLE CORE_PRODUCTION_BATCH (
    BATCH_ID STRING PRIMARY KEY,
    MACHINE_ID STRING,
    PRODUCTION_DATE DATE,
    QUANTITY_PRODUCED NUMBER,
    DEFECT_COUNT NUMBER,
    GOOD_UNITS NUMBER,
    DEFECT_PERCENT NUMBER(10,2),
    EFFICIENCY_PERCENT NUMBER(10,2),
    BATCH_STATUS STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);


-- CORE MAINTENANCE LOG TABLE
CREATE OR REPLACE TABLE CORE_MAINTENANCE_LOG (
    LOG_ID STRING PRIMARY KEY,
    MACHINE_ID STRING,
    MAINTENANCE_DATE DATE,
    ISSUE_TYPE STRING,
    RESOLVED_STATUS STRING,
    MACHINE_CONDITION STRING,
    DOWNTIME_STATUS STRING,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);


-- CORE QUALITY ALERT TABLE
CREATE OR REPLACE TABLE CORE_QUALITY_ALERT (
    ALERT_ID STRING,
    BATCH_ID STRING,
    QUALITY_SCORE NUMBER,
    ALERT_REASON STRING,
    ALERT_STATUS STRING,
    ALERT_PRIORITY STRING,
    ALERT_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);


-- VERIFY CORE TABLES
SHOW TABLES;


SELECT COUNT(*) FROM CORE.CORE_FACTORY;

SELECT COUNT(*) FROM CORE.CORE_MACHINE;

SELECT COUNT(*) FROM CORE.CORE_PRODUCTION_BATCH;


SELECT COUNT(*) FROM CORE.CORE_FACTORY;

SELECT COUNT(*) FROM CORE.CORE_MACHINE;

SELECT COUNT(*) FROM CORE.CORE_PRODUCTION_BATCH;

SELECT COUNT(*) FROM CORE.CORE_MAINTENANCE_LOG;

SELECT COUNT(*) FROM CORE.CORE_QUALITY_ALERT;


-------------------------------------------------
-- SET CONTEXT
-------------------------------------------------
USE WAREHOUSE FACTORY_ANALYTICS_WH;
USE DATABASE FACTORY_ANALYTICS_DB;
USE SCHEMA CORE;

-------------------------------------------------
-- LOAD CORE_FACTORY
-------------------------------------------------
INSERT INTO CORE_FACTORY
SELECT
    FACTORY_ID,
    FACTORY_NAME,
    CITY,
    OPERATIONAL_STATUS,
    CURRENT_TIMESTAMP()
FROM RAW.RAW_FACTORY;

-------------------------------------------------
-- LOAD CORE_MACHINE
-------------------------------------------------
INSERT INTO CORE_MACHINE
SELECT
    MACHINE_ID,
    MACHINE_NAME,
    MACHINE_TYPE,
    INSTALLATION_DATE,
    FACTORY_ID,
    'ACTIVE',
    CURRENT_TIMESTAMP()
FROM RAW.RAW_MACHINE;

-------------------------------------------------
-- LOAD CORE_PRODUCTION_BATCH
-------------------------------------------------
INSERT INTO CORE_PRODUCTION_BATCH
SELECT
    BATCH_ID,
    MACHINE_ID,
    PRODUCTION_DATE,
    QUANTITY_PRODUCED,
    DEFECT_COUNT,

    (QUANTITY_PRODUCED - DEFECT_COUNT)
    AS GOOD_UNITS,

    ROUND(
        (DEFECT_COUNT / QUANTITY_PRODUCED) * 100,
        2
    ) AS DEFECT_PERCENT,

    ROUND(
        (
            (QUANTITY_PRODUCED - DEFECT_COUNT)
            / QUANTITY_PRODUCED
        ) * 100,
        2
    ) AS EFFICIENCY_PERCENT,

    CASE
        WHEN
            (DEFECT_COUNT / QUANTITY_PRODUCED) > 0.10
        THEN 'DEFECTIVE'

        ELSE 'GOOD'
    END AS BATCH_STATUS,

    CURRENT_TIMESTAMP()

FROM RAW.RAW_PRODUCTION_BATCH

WHERE QUANTITY_PRODUCED > 0
AND DEFECT_COUNT <= QUANTITY_PRODUCED;

-------------------------------------------------
-- LOAD CORE_MAINTENANCE_LOG
-------------------------------------------------
INSERT INTO CORE_MAINTENANCE_LOG
SELECT
    LOG_ID,
    MACHINE_ID,
    MAINTENANCE_DATE,
    ISSUE_TYPE,
    RESOLVED_STATUS,

    CASE
        WHEN RESOLVED_STATUS = 'Resolved'
        THEN 'STABLE'

        ELSE 'ATTENTION_REQUIRED'
    END AS MACHINE_CONDITION,

    CASE
        WHEN ISSUE_TYPE IS NOT NULL
        THEN 'DOWN'

        ELSE 'RUNNING'
    END AS DOWNTIME_STATUS,

    CURRENT_TIMESTAMP()

FROM RAW.RAW_MAINTENANCE_LOG;

-------------------------------------------------
-- LOAD CORE_QUALITY_ALERT
-------------------------------------------------
INSERT INTO CORE_QUALITY_ALERT
SELECT
    RAW_DATA:ALERT_ID::STRING,
    RAW_DATA:BATCH_ID::STRING,
    RAW_DATA:QUALITY_SCORE::NUMBER,
    RAW_DATA:ALERT_REASON::STRING,
    RAW_DATA:ALERT_STATUS::STRING,

    CASE
        WHEN RAW_DATA:QUALITY_SCORE::NUMBER < 70
        THEN 'HIGH'

        WHEN RAW_DATA:QUALITY_SCORE::NUMBER
             BETWEEN 70 AND 85
        THEN 'MEDIUM'

        ELSE 'LOW'
    END AS ALERT_PRIORITY,

    CURRENT_TIMESTAMP()

FROM RAW.RAW_QUALITY_ALERT;

-------------------------------------------------
-- VERIFY CORE TABLES
-------------------------------------------------
SELECT COUNT(*) FROM CORE_FACTORY;

SELECT COUNT(*) FROM CORE_MACHINE;

SELECT COUNT(*) FROM CORE_PRODUCTION_BATCH;

SELECT COUNT(*) FROM CORE_MAINTENANCE_LOG;

SELECT COUNT(*) FROM CORE_QUALITY_ALERT;