-- SET CONTEXT
USE WAREHOUSE FACTORY_ANALYTICS_WH;
USE DATABASE FACTORY_ANALYTICS_DB;
USE SCHEMA MART;


-- DYNAMIC TABLE :
-- FACTORY ANALYTICS
CREATE OR REPLACE DYNAMIC TABLE DT_FACTORY_ANALYTICS
TARGET_LAG = '1 MINUTES'
WAREHOUSE = FACTORY_ANALYTICS_WH
AS

SELECT

    F.FACTORY_NAME,

    SUM(P.QUANTITY_PRODUCED) AS TOTAL_PRODUCTION,

    SUM(P.DEFECT_COUNT) AS TOTAL_DEFECTS,

    AVG(P.EFFICIENCY_PERCENT) AS AVG_EFFICIENCY,

    SUM(P.GOOD_UNITS) AS TOTAL_GOOD_UNITS

FROM FACT_PRODUCTION P

JOIN DIM_FACTORY F
ON P.FACTORY_KEY = F.FACTORY_KEY

GROUP BY
    F.FACTORY_NAME;


-- DYNAMIC TABLE :
-- MACHINE PERFORMANCE
CREATE OR REPLACE DYNAMIC TABLE DT_MACHINE_PERFORMANCE
TARGET_LAG = '5 MINUTES'
WAREHOUSE = FACTORY_ANALYTICS_WH
AS

SELECT

    M.MACHINE_NAME,

    M.MACHINE_TYPE,

    AVG(P.EFFICIENCY_PERCENT) AS AVG_MACHINE_EFFICIENCY,

    AVG(P.DEFECT_PERCENT) AS AVG_DEFECT_PERCENT,

    SUM(P.QUANTITY_PRODUCED) AS TOTAL_OUTPUT

FROM FACT_PRODUCTION P

JOIN DIM_MACHINE M
ON P.MACHINE_KEY = M.MACHINE_KEY

GROUP BY
    M.MACHINE_NAME,
    M.MACHINE_TYPE;


-- DYNAMIC TABLE :
-- DEFECT ANALYTICS
CREATE OR REPLACE DYNAMIC TABLE DT_DEFECT_ANALYTICS
TARGET_LAG = '1 MINUTES'
WAREHOUSE = FACTORY_ANALYTICS_WH
AS

SELECT

    BATCH_STATUS,

    COUNT(*) AS TOTAL_BATCHES,

    AVG(DEFECT_PERCENT) AS AVG_DEFECT_PERCENT,

    SUM(DEFECT_COUNT) AS TOTAL_DEFECTS

FROM FACT_PRODUCTION

GROUP BY
    BATCH_STATUS;


-- VERIFY DYNAMIC TABLES
SHOW DYNAMIC TABLES;