-- SET CONTEXT
USE WAREHOUSE FACTORY_ANALYTICS_WH;
USE DATABASE FACTORY_ANALYTICS_DB;
USE SCHEMA MART;


-- LOAD DIM_FACTORY
INSERT INTO DIM_FACTORY (
    FACTORY_ID,
    FACTORY_NAME,
    CITY,
    OPERATIONAL_STATUS
)
SELECT
    FACTORY_ID,
    FACTORY_NAME,
    CITY,
    OPERATIONAL_STATUS
FROM CORE.CORE_FACTORY;


-- LOAD DIM_MACHINE
INSERT INTO DIM_MACHINE (
    MACHINE_ID,
    MACHINE_NAME,
    MACHINE_TYPE,
    INSTALLATION_DATE,
    FACTORY_ID,
    MACHINE_STATUS
)
SELECT
    MACHINE_ID,
    MACHINE_NAME,
    MACHINE_TYPE,
    INSTALLATION_DATE,
    FACTORY_ID,
    MACHINE_STATUS
FROM CORE.CORE_MACHINE;


-- LOAD DIM_DATE
INSERT INTO DIM_DATE
SELECT DISTINCT

    TO_NUMBER(
        TO_CHAR(PRODUCTION_DATE,'YYYYMMDD')
    ) AS DATE_KEY,

    PRODUCTION_DATE AS FULL_DATE,

    DAY(PRODUCTION_DATE) AS DAY,

    MONTH(PRODUCTION_DATE) AS MONTH,

    YEAR(PRODUCTION_DATE) AS YEAR,

    QUARTER(PRODUCTION_DATE) AS QUARTER

FROM CORE.CORE_PRODUCTION_BATCH;





-- LOAD FACT_PRODUCTION
INSERT INTO FACT_PRODUCTION (

    BATCH_ID,

    MACHINE_KEY,
    FACTORY_KEY,
    DATE_KEY,

    QUANTITY_PRODUCED,
    DEFECT_COUNT,
    GOOD_UNITS,

    DEFECT_PERCENT,
    EFFICIENCY_PERCENT,

    BATCH_STATUS
)

SELECT

    P.BATCH_ID,

    M.MACHINE_KEY,

    F.FACTORY_KEY,

    TO_NUMBER(
        TO_CHAR(P.PRODUCTION_DATE,'YYYYMMDD')
    ) AS DATE_KEY,

    P.QUANTITY_PRODUCED,

    P.DEFECT_COUNT,

    P.GOOD_UNITS,

    P.DEFECT_PERCENT,

    P.EFFICIENCY_PERCENT,

    P.BATCH_STATUS

FROM CORE.CORE_PRODUCTION_BATCH P

JOIN DIM_MACHINE M
ON P.MACHINE_ID = M.MACHINE_ID

JOIN DIM_FACTORY F
ON M.FACTORY_ID = F.FACTORY_ID;

SELECT * FROM FACT_PRODUCTION;