
-- SET ROLE
USE ROLE ACCOUNTADMIN;


-- CREATE ROLES
CREATE OR REPLACE ROLE ADMIN_ROLE;

CREATE OR REPLACE ROLE ANALYST_ROLE;

CREATE OR REPLACE ROLE QUALITY_MANAGER_ROLE;

CREATE OR REPLACE ROLE FACTORY_MANAGER_ROLE;


-- GRANT WAREHOUSE ACCESS
GRANT USAGE
ON WAREHOUSE FACTORY_ANALYTICS_WH
TO ROLE ADMIN_ROLE;

GRANT USAGE
ON WAREHOUSE FACTORY_ANALYTICS_WH
TO ROLE ANALYST_ROLE;

GRANT USAGE
ON WAREHOUSE FACTORY_ANALYTICS_WH
TO ROLE QUALITY_MANAGER_ROLE;

GRANT USAGE
ON WAREHOUSE FACTORY_ANALYTICS_WH
TO ROLE FACTORY_MANAGER_ROLE;


-- GRANT DATABASE ACCESS
GRANT USAGE
ON DATABASE FACTORY_ANALYTICS_DB
TO ROLE ADMIN_ROLE;

GRANT USAGE
ON DATABASE FACTORY_ANALYTICS_DB
TO ROLE ANALYST_ROLE;

GRANT USAGE
ON DATABASE FACTORY_ANALYTICS_DB
TO ROLE QUALITY_MANAGER_ROLE;

GRANT USAGE
ON DATABASE FACTORY_ANALYTICS_DB
TO ROLE FACTORY_MANAGER_ROLE;


-- GRANT SCHEMA ACCESS
GRANT USAGE
ON SCHEMA FACTORY_ANALYTICS_DB.RAW
TO ROLE ADMIN_ROLE;

GRANT USAGE
ON SCHEMA FACTORY_ANALYTICS_DB.CORE
TO ROLE ADMIN_ROLE;

GRANT USAGE
ON SCHEMA FACTORY_ANALYTICS_DB.MART
TO ROLE ADMIN_ROLE;


-- ANALYST ROLE ACCESS
GRANT USAGE
ON SCHEMA FACTORY_ANALYTICS_DB.MART
TO ROLE ANALYST_ROLE;

GRANT SELECT
ON ALL TABLES IN SCHEMA FACTORY_ANALYTICS_DB.MART
TO ROLE ANALYST_ROLE;

GRANT SELECT
ON ALL VIEWS IN SCHEMA FACTORY_ANALYTICS_DB.MART
TO ROLE ANALYST_ROLE;


-- QUALITY MANAGER ACCESS
GRANT USAGE
ON SCHEMA FACTORY_ANALYTICS_DB.CORE
TO ROLE QUALITY_MANAGER_ROLE;

GRANT SELECT
ON ALL TABLES IN SCHEMA FACTORY_ANALYTICS_DB.CORE
TO ROLE QUALITY_MANAGER_ROLE;


-- FACTORY MANAGER ACCESS
GRANT USAGE
ON SCHEMA FACTORY_ANALYTICS_DB.MART
TO ROLE FACTORY_MANAGER_ROLE;

GRANT SELECT
ON ALL TABLES IN SCHEMA FACTORY_ANALYTICS_DB.MART
TO ROLE FACTORY_MANAGER_ROLE;


-- CREATE MASKING POLICY
USE DATABASE FACTORY_ANALYTICS_DB;
USE SCHEMA MART;

ALTER TABLE MART.DIM_FACTORY
MODIFY COLUMN FACTORY_NAME
UNSET MASKING POLICY;

CREATE OR REPLACE MASKING POLICY MASK_FACTORY_NAME
AS (VAL STRING)
RETURNS STRING ->

CASE
    WHEN CURRENT_ROLE() IN ('ADMIN_ROLE')
    THEN VAL

    ELSE 'MASKED_FACTORY'
END;


-- APPLY MASKING POLICY
ALTER TABLE MART.DIM_FACTORY
MODIFY COLUMN FACTORY_NAME
SET MASKING POLICY MASK_FACTORY_NAME;


-- GRANT ROLES TO CURRENT USER
GRANT ROLE ADMIN_ROLE TO USER AI2213;
GRANT ROLE ANALYST_ROLE TO USER AI2213;
GRANT ROLE QUALITY_MANAGER_ROLE TO USER AI2213;
GRANT ROLE FACTORY_MANAGER_ROLE TO USER AI2213;


-- VERIFY MASKING
USE ROLE ANALYST_ROLE;

SELECT * FROM MART.DIM_FACTORY;


-- SWITCH BACK TO ADMIN
USE ROLE ACCOUNTADMIN;

-- VERIFY ROLES
SHOW ROLES;


-- VERIFY GRANTS
SHOW GRANTS TO ROLE ANALYST_ROLE;
SHOW GRANTS TO ROLE QUALITY_MANAGER_ROLE;
SHOW GRANTS TO ROLE FACTORY_MANAGER_ROLE;