-- SET CONTEXT
USE WAREHOUSE FACTORY_ANALYTICS_WH;
USE DATABASE FACTORY_ANALYTICS_DB;
USE SCHEMA MART;


-- DIM_FACTORY
CREATE OR REPLACE TABLE DIM_FACTORY (
    FACTORY_KEY INTEGER AUTOINCREMENT,
    FACTORY_ID STRING,
    FACTORY_NAME STRING,
    CITY STRING,
    OPERATIONAL_STATUS STRING
);


-- DIM_MACHINE
CREATE OR REPLACE TABLE DIM_MACHINE (
    MACHINE_KEY INTEGER AUTOINCREMENT,
    MACHINE_ID STRING,
    MACHINE_NAME STRING,
    MACHINE_TYPE STRING,
    INSTALLATION_DATE DATE,
    FACTORY_ID STRING,
    MACHINE_STATUS STRING
);


-- DIM_DATE
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY INTEGER,
    FULL_DATE DATE,
    DAY NUMBER,
    MONTH NUMBER,
    YEAR NUMBER,
    QUARTER NUMBER
);


-- FACT_PRODUCTION
CREATE OR REPLACE TABLE FACT_PRODUCTION (
    PRODUCTION_KEY INTEGER AUTOINCREMENT,

    BATCH_ID STRING,

    MACHINE_KEY INTEGER,
    FACTORY_KEY INTEGER,
    DATE_KEY INTEGER,

    QUANTITY_PRODUCED NUMBER,
    DEFECT_COUNT NUMBER,
    GOOD_UNITS NUMBER,

    DEFECT_PERCENT NUMBER(10,2),
    EFFICIENCY_PERCENT NUMBER(10,2),

    BATCH_STATUS STRING
);


-- VERIFY TABLES
SHOW TABLES;

SELECT* FROM FACT_PRODUCTION;