-- SET CONTEXT
USE WAREHOUSE FACTORY_ANALYTICS_WH;
USE DATABASE FACTORY_ANALYTICS_DB;
USE SCHEMA MART;


-- MATERIALIZED VIEW :
CREATE OR REPLACE MATERIALIZED VIEW MV_PRODUCTION_SUMMARY AS

SELECT

    DATE_KEY,

    SUM(QUANTITY_PRODUCED) AS TOTAL_PRODUCTION,

    SUM(DEFECT_COUNT) AS TOTAL_DEFECTS,

    SUM(GOOD_UNITS) AS TOTAL_GOOD_UNITS,

    AVG(EFFICIENCY_PERCENT) AS AVG_EFFICIENCY

FROM FACT_PRODUCTION

GROUP BY DATE_KEY;


-- MACHINE PERFORMANCE
CREATE OR REPLACE MATERIALIZED VIEW MV_MACHINE_PERFORMANCE AS

SELECT

    MACHINE_KEY,

    AVG(EFFICIENCY_PERCENT) AS AVG_MACHINE_EFFICIENCY,

    AVG(DEFECT_PERCENT) AS AVG_DEFECT_PERCENT,

    SUM(QUANTITY_PRODUCED) AS TOTAL_OUTPUT

FROM FACT_PRODUCTION

GROUP BY MACHINE_KEY;

SHOW MATERIALIZED VIEWS;