--SET CONTEXT
USE WAREHOUSE FACTORY_ANALYTICS_WH;
USE DATABASE FACTORY_ANALYTICS_DB;
USE SCHEMA RAW;

--CREATE RAW TABLE
-- RAW_FACTORY TABLE
CREATE OR REPLACE TABLE RAW_FACTORY (
    FACTORY_ID STRING,
    FACTORY_NAME STRING,
    CITY STRING,
    OPERATIONAL_STATUS STRING
);

-- RAW_MACHINE TABLE
CREATE OR REPLACE TABLE RAW_MACHINE (
    MACHINE_ID STRING,
    MACHINE_NAME STRING,
    MACHINE_TYPE STRING,
    INSTALLATION_DATE DATE,
    FACTORY_ID STRING
);

-- RAW_PRODUCTION_BATCH TABLE
CREATE OR REPLACE TABLE RAW_PRODUCTION_BATCH (
    BATCH_ID STRING,
    MACHINE_ID STRING,
    PRODUCTION_DATE DATE,
    QUANTITY_PRODUCED NUMBER,
    DEFECT_COUNT NUMBER
);

-- RAW_MAINTENANCE_LOG TABLE
CREATE OR REPLACE TABLE RAW_MAINTENANCE_LOG (
    LOG_ID STRING,
    MACHINE_ID STRING,
    MAINTENANCE_DATE DATE,
    ISSUE_TYPE STRING,
    RESOLVED_STATUS STRING
);

-- RAW_QUALITY_ALERT TABLE
CREATE OR REPLACE TABLE RAW_QUALITY_ALERT (
    RAW_DATA VARIANT
);


SELECT* FROM RAW_FACTORY;


-- SETUP CSV FILE FORMAT
CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
EMPTY_FIELD_AS_NULL = TRUE
TRIM_SPACE = TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

-- SETUP JSON FILE FORMAT
CREATE OR REPLACE FILE FORMAT JSON_FILE_FORMAT
TYPE = 'JSON'
STRIP_OUTER_ARRAY = TRUE;

-- CREATE CSV STAGE
CREATE OR REPLACE STAGE CSV_STAGE
URL='s3://manufacturinganalytics123'
CREDENTIALS=(
        AWS_KEY_ID='key'
        AWS_SECRET_KEY='secret key'
)
FILE_FORMAT = CSV_FILE_FORMAT;


-- CREATE JSON STAGE
CREATE OR REPLACE STAGE JSON_STAGE
URL='s3://manufacturinganalytics123'
CREDENTIALS=(
        AWS_KEY_ID='key'
        AWS_SECRET_KEY='secret key'
)
FILE_FORMAT = JSON_FILE_FORMAT;


COPY INTO RAW_FACTORY
FROM @CSV_STAGE/factory.csv
FILE_FORMAT = CSV_FILE_FORMAT
FORCE=TRUE;

COPY INTO RAW_MACHINE
FROM @CSV_STAGE/machine.csv
FILE_FORMAT = CSV_FILE_FORMAT
FORCE=TRUE;


COPY INTO RAW_PRODUCTION_BATCH
FROM @CSV_STAGE/production_batch.csv
FILE_FORMAT = CSV_FILE_FORMAT
FORCE=TRUE;


COPY INTO RAW_MAINTENANCE_LOG
FROM @CSV_STAGE/maintenance_log.csv
FILE_FORMAT = CSV_FILE_FORMAT
FORCE = TRUE;

COPY INTO RAW_QUALITY_ALERT
FROM @JSON_STAGE/quality_alert1.json
FILE_FORMAT = JSON_FILE_FORMAT
FORCE=TRUE;





-- VERIFY RAW TABLE DATA

SELECT * FROM RAW_FACTORY;

SELECT * FROM RAW_MACHINE;

SELECT * FROM RAW_PRODUCTION_BATCH;

SELECT * FROM RAW_MAINTENANCE_LOG;

SELECT * FROM RAW_QUALITY_ALERT;

LIST @CSV_STAGE;

LIST @JSON_STAGE;

