
-- SET CONTEXT
USE WAREHOUSE FACTORY_ANALYTICS_WH;
USE DATABASE FACTORY_ANALYTICS_DB;
USE SCHEMA RAW;


-- PIPE : FACTORY
CREATE OR REPLACE PIPE PIPE_FACTORY_NEW
AUTO_INGEST = TRUE
AS
COPY INTO RAW_FACTORY
FROM @CSV_STAGE
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
PATTERN = '.*factory.*.csv';


-- PIPE : MACHINE
CREATE OR REPLACE PIPE PIPE_MACHINE_NEW
AUTO_INGEST = TRUE
AS
COPY INTO RAW_MACHINE
FROM @CSV_STAGE
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
PATTERN = '.*machine.*.csv';


-- PIPE : PRODUCTION BATCH
CREATE OR REPLACE PIPE PIPE_PRODUCTION_BATCH_NEW
AUTO_INGEST = TRUE
AS
COPY INTO RAW_PRODUCTION_BATCH
FROM @CSV_STAGE
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
PATTERN = '.*production_batch.*.csv';


-- PIPE : MAINTENANCE LOG
CREATE OR REPLACE PIPE PIPE_MAINTENANCE_LOG_NEW
AUTO_INGEST = TRUE
AS
COPY INTO RAW_MAINTENANCE_LOG
FROM @CSV_STAGE
FILE_FORMAT = (FORMAT_NAME = CSV_FILE_FORMAT)
PATTERN = '.*maintenance_log.*.csv';


-- PIPE : QUALITY ALERT JSON
CREATE OR REPLACE PIPE PIPE_QUALITY_ALERT_NEW
AUTO_INGEST = TRUE
AS
COPY INTO RAW_QUALITY_ALERT
FROM @JSON_STAGE
FILE_FORMAT = (FORMAT_NAME = JSON_FILE_FORMAT)
PATTERN = '.*quality_alert.*.json';


-- REFRESH PIPES
ALTER PIPE PIPE_FACTORY_NEW REFRESH;

ALTER PIPE PIPE_MACHINE_NEW REFRESH;

ALTER PIPE PIPE_PRODUCTION_BATCH_NEW REFRESH;

ALTER PIPE PIPE_MAINTENANCE_LOG_NEW REFRESH;

ALTER PIPE PIPE_QUALITY_ALERT_NEW REFRESH;


-- VERIFY PIPES
SHOW PIPES;