-- SET CONTEXT
USE WAREHOUSE FACTORY_ANALYTICS_WH;
USE DATABASE FACTORY_ANALYTICS_DB;
USE SCHEMA RAW;


-- STREAM : FACTORY
CREATE OR REPLACE STREAM STREAM_FACTORY
ON TABLE RAW_FACTORY;

-- STREAM : MACHINE
CREATE OR REPLACE STREAM STREAM_MACHINE
ON TABLE RAW_MACHINE;


-- STREAM : PRODUCTION BATCH
CREATE OR REPLACE STREAM STREAM_PRODUCTION_BATCH
ON TABLE RAW_PRODUCTION_BATCH;


-- STREAM : MAINTENANCE LOG
CREATE OR REPLACE STREAM STREAM_MAINTENANCE_LOG
ON TABLE RAW_MAINTENANCE_LOG;


-- STREAM : QUALITY ALERT JSON
CREATE OR REPLACE STREAM STREAM_QUALITY_ALERT
ON TABLE RAW_QUALITY_ALERT;


-- VERIFY STREAMS
SHOW STREAMS;


-- VERIFY STREAM DATA

SELECT * FROM STREAM_FACTORY;

SELECT * FROM STREAM_MACHINE;

SELECT * FROM STREAM_PRODUCTION_BATCH;

SELECT * FROM STREAM_MAINTENANCE_LOG;

SELECT * FROM STREAM_QUALITY_ALERT;