-- SET CONTEXT
USE WAREHOUSE FACTORY_ANALYTICS_WH;
USE DATABASE FACTORY_ANALYTICS_DB;
USE SCHEMA CORE;


-- TASK : FACTORY
CREATE OR REPLACE TASK TASK_FACTORY
WAREHOUSE = FACTORY_ANALYTICS_WH
SCHEDULE = '1 MINUTE'
AS

INSERT INTO CORE_FACTORY
SELECT DISTINCT
    FACTORY_ID,
    FACTORY_NAME,
    CITY,
    OPERATIONAL_STATUS,
    CURRENT_TIMESTAMP()
FROM RAW.STREAM_FACTORY;


-- TASK : MACHINE
CREATE OR REPLACE TASK TASK_MACHINE
WAREHOUSE = FACTORY_ANALYTICS_WH
SCHEDULE = '1 MINUTE'
AS

INSERT INTO CORE_MACHINE
SELECT
    MACHINE_ID,
    MACHINE_NAME,
    MACHINE_TYPE,
    INSTALLATION_DATE,
    FACTORY_ID,
    'ACTIVE',
    CURRENT_TIMESTAMP()

FROM (
    SELECT *,
           ROW_NUMBER() OVER(
               PARTITION BY MACHINE_ID
               ORDER BY INSTALLATION_DATE DESC
           ) AS RN
    FROM RAW.STREAM_MACHINE
)
WHERE RN = 1;


-- TASK : PRODUCTION BATCH
CREATE OR REPLACE TASK TASK_PRODUCTION_BATCH
WAREHOUSE = FACTORY_ANALYTICS_WH
SCHEDULE = '1 MINUTE'
AS

INSERT INTO CORE_PRODUCTION_BATCH
SELECT
    P.BATCH_ID,
    P.MACHINE_ID,
    P.PRODUCTION_DATE,
    P.QUANTITY_PRODUCED,
    P.DEFECT_COUNT,

    -- GOOD UNITS
    (P.QUANTITY_PRODUCED - P.DEFECT_COUNT)
    AS GOOD_UNITS,

    
    -- DEFECT PERCENT
    ROUND(
        (P.DEFECT_COUNT / P.QUANTITY_PRODUCED) * 100,
        2
    ) AS DEFECT_PERCENT,

    -- EFFICIENCY PERCENT
    ROUND(
        (
            (P.QUANTITY_PRODUCED - P.DEFECT_COUNT)
            / P.QUANTITY_PRODUCED
        ) * 100,
        2
    ) AS EFFICIENCY_PERCENT,

    -- BATCH STATUS
    CASE
        WHEN
            (P.DEFECT_COUNT / P.QUANTITY_PRODUCED) > 0.10
        THEN 'DEFECTIVE'
        ELSE 'GOOD'
    END AS BATCH_STATUS,

    CURRENT_TIMESTAMP()

FROM RAW.STREAM_PRODUCTION_BATCH P

JOIN CORE_MACHINE M
ON P.MACHINE_ID = M.MACHINE_ID

JOIN CORE_FACTORY F
ON M.FACTORY_ID = F.FACTORY_ID

-- BUSINESS RULES

WHERE P.QUANTITY_PRODUCED > 0
AND P.DEFECT_COUNT <= P.QUANTITY_PRODUCED
AND F.OPERATIONAL_STATUS != 'Closed';


-- TASK : MAINTENANCE LOG
CREATE OR REPLACE TASK TASK_MAINTENANCE_LOG
WAREHOUSE = FACTORY_ANALYTICS_WH
SCHEDULE = '1 MINUTE'
AS

INSERT INTO CORE_MAINTENANCE_LOG
SELECT
    LOG_ID,
    MACHINE_ID,
    MAINTENANCE_DATE,
    ISSUE_TYPE,
    RESOLVED_STATUS,

    -- MACHINE CONDITION
    
    CASE
        WHEN RESOLVED_STATUS = 'Resolved'
        THEN 'STABLE'
        ELSE 'ATTENTION_REQUIRED'
    END AS MACHINE_CONDITION,

    -- DOWNTIME STATUS
    
    CASE
        WHEN ISSUE_TYPE IS NOT NULL
        THEN 'DOWN'
        ELSE 'RUNNING'
    END AS DOWNTIME_STATUS,

    CURRENT_TIMESTAMP()

FROM RAW.STREAM_MAINTENANCE_LOG

-- INVALID RECORD REJECTION
WHERE ISSUE_TYPE IS NOT NULL;


-- TASK : QUALITY ALERT
CREATE OR REPLACE TASK TASK_QUALITY_ALERT
WAREHOUSE = FACTORY_ANALYTICS_WH
SCHEDULE = '1 MINUTE'
AS

INSERT INTO CORE_QUALITY_ALERT
SELECT
    RAW_DATA:ALERT_ID::STRING,
    RAW_DATA:BATCH_ID::STRING,
    RAW_DATA:QUALITY_SCORE::NUMBER,
    RAW_DATA:ALERT_REASON::STRING,
    RAW_DATA:ALERT_STATUS::STRING,

    
    -- ALERT PRIORITY

    CASE
        WHEN RAW_DATA:QUALITY_SCORE::NUMBER < 70
        THEN 'HIGH'

        WHEN RAW_DATA:QUALITY_SCORE::NUMBER
             BETWEEN 70 AND 85
        THEN 'MEDIUM'

        ELSE 'LOW'
    END AS ALERT_PRIORITY,

    CURRENT_TIMESTAMP()

FROM RAW.STREAM_QUALITY_ALERT;


-- START TASKS
ALTER TASK TASK_FACTORY SUSPEND;
ALTER TASK TASK_MACHINE SUSPEND;
ALTER TASK TASK_PRODUCTION_BATCH SUSPEND;
ALTER TASK TASK_MAINTENANCE_LOG SUSPEND;
ALTER TASK TASK_QUALITY_ALERT SUSPEND;


-- VERIFY TASKS
SHOW TASKS;

SHOW TASKS LIKE 'TASK_FACTORY';


SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.TASK_HISTORY()
)
ORDER BY SCHEDULED_TIME DESC;