-- SET CONTEXT
USE WAREHOUSE FACTORY_ANALYTICS_WH;
USE DATABASE FACTORY_ANALYTICS_DB;
USE SCHEMA MART;


CREATE OR REPLACE VIEW VW_MAINTENANCE_ANALYTICS AS

SELECT
    LOG_ID,
    MACHINE_ID,
    ISSUE_TYPE,
    RESOLVED_STATUS,
    MACHINE_CONDITION,
    DOWNTIME_STATUS
FROM CORE.CORE_MAINTENANCE_LOG;


CREATE OR REPLACE VIEW VW_QUALITY_ALERT_ANALYTICS AS

SELECT
    ALERT_ID,
    BATCH_ID,
    QUALITY_SCORE,
    ALERT_REASON,
    ALERT_STATUS,
    ALERT_PRIORITY
FROM CORE.CORE_QUALITY_ALERT;


-- VIEW : PRODUCTION EFFICIENCY
CREATE OR REPLACE VIEW VW_PRODUCTION_EFFICIENCY AS

SELECT
    F.FACTORY_NAME,
    M.MACHINE_NAME,
    D.FULL_DATE,

    SUM(P.QUANTITY_PRODUCED) AS TOTAL_PRODUCTION,

    SUM(P.DEFECT_COUNT) AS TOTAL_DEFECTS,

    AVG(P.EFFICIENCY_PERCENT) AS AVG_EFFICIENCY

FROM FACT_PRODUCTION P

JOIN DIM_FACTORY F
ON P.FACTORY_KEY = F.FACTORY_KEY

JOIN DIM_MACHINE M
ON P.MACHINE_KEY = M.MACHINE_KEY

JOIN DIM_DATE D
ON P.DATE_KEY = D.DATE_KEY

GROUP BY
    F.FACTORY_NAME,
    M.MACHINE_NAME,
    D.FULL_DATE;


-- VIEW : DEFECT ANALYSIS
CREATE OR REPLACE VIEW VW_DEFECT_ANALYSIS AS

SELECT
    F.FACTORY_NAME,

    M.MACHINE_NAME,

    SUM(P.DEFECT_COUNT) AS TOTAL_DEFECTS,

    AVG(P.DEFECT_PERCENT) AS AVG_DEFECT_PERCENT

FROM FACT_PRODUCTION P

JOIN DIM_FACTORY F
ON P.FACTORY_KEY = F.FACTORY_KEY

JOIN DIM_MACHINE M
ON P.MACHINE_KEY = M.MACHINE_KEY

GROUP BY
    F.FACTORY_NAME,
    M.MACHINE_NAME;


-- VIEW : FACTORY PERFORMANCE
CREATE OR REPLACE VIEW VW_FACTORY_PERFORMANCE AS

SELECT
    F.FACTORY_NAME,

    SUM(P.QUANTITY_PRODUCED) AS TOTAL_OUTPUT,

    SUM(P.GOOD_UNITS) AS GOOD_UNITS,

    AVG(P.EFFICIENCY_PERCENT) AS FACTORY_EFFICIENCY

FROM FACT_PRODUCTION P

JOIN DIM_FACTORY F
ON P.FACTORY_KEY = F.FACTORY_KEY

GROUP BY
    F.FACTORY_NAME;

-- VIEW : MACHINE DOWNTIME
CREATE OR REPLACE VIEW VW_MACHINE_DOWNTIME AS

SELECT
    MACHINE_ID,

    ISSUE_TYPE,

    RESOLVED_STATUS,

    MACHINE_CONDITION,

    DOWNTIME_STATUS,

    COUNT(*) AS ISSUE_COUNT

FROM CORE.CORE_MAINTENANCE_LOG

GROUP BY
    MACHINE_ID,
    ISSUE_TYPE,
    RESOLVED_STATUS,
    MACHINE_CONDITION,
    DOWNTIME_STATUS;


-- VERIFY VIEWS
SHOW VIEWS;

SELECT* FROM VW_MACHINE_DOWNTIME;


SELECT COUNT(DISTINCT FACTORY_ID)
FROM MART.DIM_FACTORY;

SELECT *
FROM MART.DIM_FACTORY;